config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "password", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "password", except: [:destroy]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
      <h2><%= @article.errors.count %>件のエラーが存在します</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: 'form-control' %>
  </div>

  <p>
    <%= f.submit '投稿', class: 'btn btn-default' %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>記事の編集</h1>
 
<%= render 'form' %>

<%= link_to '戻る', articles_path %>

app/views/articles/index.html.erb
<h1>ブログ</h1>

<table class="table">
  <tr>
    <th>タイトル</th>
    <th>本文</th>
    <th colspan="3"></th>
  </tr>
 
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to '開く', article_path(article), class: 'btn btn-default pull-right' %></td>
    <td><%= link_to '編集', edit_article_path(article), class: 'btn btn-default pull-right' %></td>
    <td><%= link_to '削除', article_path(article),
                    method: :delete, data: { confirm: '本当に削除しますか' },
                    class: 'btn btn-default pull-right' %></td>
  </tr>
<% end %>
</table>

<hr>


<%= link_to '新規', new_article_path, class: 'btn btn-default' %>

app/views/articles/new.html.erb
<h1>新規記事</h1>
<%= render 'form' %>

<%= link_to '戻る', articles_path %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
 
<p>
  <%= @article.text %>
</p>

<h3>コメント</h3>
<%= render @article.comments %>

<h3>コメントを追加する</h3>
<%= render "comments/form" %>

<hr>

<p><%= link_to '戻る', articles_path %> | <%= link_to '編集', edit_article_path(@article) %></p>

app/views/comments/_comment.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> <%= comment.commenter %> </h3>
  </div>
  <div class="panel-body">
    <p>
      <%= comment.body %>
    </p>

    <p>
      <%= link_to '削除', [comment.article, comment],
                   method: :delete,
                   data: { confirm: '本当に削除しますか？'},
                   class: 'btn btn-default pull-right' %>
    </p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <div class="form-group">
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <%= f.submit '投稿', class: 'btn btn-default' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ブログ サンプル</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Sample</a>
    </div>
  </div>
</nav>

<div class="container">

    <%= yield %>

</div><!-- /.container -->

</body>
</html>